[
  { "id": "src-量子", "name": "量子", "Top": true, "Search": true, "Priority": 500001, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://cj.lziapi.com/api.php/provide/vod/from/lzm3u8/" },
  { "id": "src-电影天堂", "name": "电影天堂", "Top": true, "Search": true, "Priority": 500002, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://caiji.dyttzyapi.com/api.php/provide/vod/" },
  { "id": "src-如意", "name": "如意", "Top": true, "Search": true, "Priority": 500003, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://cj.rycjapi.com/api.php/provide/vod/from/rym3u8/at/json/" },
  { "id": "src-非凡", "name": "非凡", "Top": true, "Search": true, "Priority": 500004, "note": "use_proxy=true enabled=true is_custom=true", "api": "http://cj.ffzyapi.com/api.php/provide/vod/at/json/" },
  { "id": "src-极速", "name": "极速", "Top": true, "Search": true, "Priority": 500005, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://jszyapi.com/api.php/provide/vod/from/jsm3u8/at/json" },
  { "id": "src-暴风", "name": "暴风", "Top": true, "Search": true, "Priority": 500006, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://bfzyapi.com/api.php/provide/vod/" },
  { "id": "src-最大", "name": "最大", "Top": true, "Search": true, "Priority": 500007, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://api.zuidapi.com/api.php/provide/vod/from/zuidam3u8/" },
  { "id": "src-360", "name": "360", "Top": true, "Search": true, "Priority": 500008, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://360zy.com/api.php/provide/vod" },
  { "id": "src-四圈", "name": "四圈", "Top": true, "Search": true, "Priority": 500009, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://pg.fenwe078.cf/api.php/provide/vod/" },
  { "id": "src-ikun", "name": "ikun", "Top": false, "Search": true, "Priority": 500010, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://ikunzyapi.com/api.php/provide/vod/" },
  { "id": "src-卧龙", "name": "卧龙", "Top": true, "Search": true, "Priority": 500011, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://collect.wolongzyw.com/api.php/provide/vod/at/json" },
  { "id": "src-无尽", "name": "无尽", "Top": true, "Search": true, "Priority": 500012, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://api.wujinapi.me/api.php/provide/vod/from/wjm3u8/at/json/" },
  { "id": "src-速播", "name": "速播", "Top": true, "Search": true, "Priority": 500013, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://subocaiji.com/api.php/provide/vod/at/json" },
  { "id": "src-爱奇艺", "name": "爱奇艺", "Top": false, "Search": true, "Priority": 500014, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://iqiyizyapi.com/api.php/provide/vod" },
  { "id": "src-爱坤", "name": "爱坤", "Top": false, "Search": true, "Priority": 500015, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://ikunzyapi.com/api.php/provide/vod" },
  { "id": "src-虎牙", "name": "虎牙", "Top": false, "Search": true, "Priority": 500016, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://www.huyaapi.com/api.php/provide/vod/at/json" },
  { "id": "src-艾旦影视", "name": "艾旦影视", "Top": false, "Search": true, "Priority": 500017, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://lovedan.net/api.php/provide/vod/" },
  { "id": "src-光速资源", "name": "光速资源", "Top": false, "Search": true, "Priority": 500018, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://api.guangsuapi.com/api.php/provide/vod/from/gsm3u8/" },
  { "id": "src-豪华资源", "name": "豪华资源", "Top": false, "Search": true, "Priority": 500019, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://hhzyapi.com/api.php/provide/vod/at/json" },
  { "id": "src-金鹰资源", "name": "金鹰资源", "Top": false, "Search": true, "Priority": 500020, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://jyzyapi.com/provide/vod/from/jinyingm3u8/" },
  { "id": "src-猫眼资源", "name": "猫眼资源", "Top": false, "Search": true, "Priority": 500021, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://api.maoyanapi.top/api.php/provide/vod" },
  { "id": "src-789", "name": "789", "Top": false, "Search": true, "Priority": 500022, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://www.caiji.cyou/api.php/provide/vod/?ac=list" },
  { "id": "src-听风", "name": "听风", "Top": false, "Search": true, "Priority": 500023, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://gctf.tfdh.top/api.php/provide/vod/?ac=list" },
  { "id": "src-U酷", "name": "U酷", "Top": false, "Search": true, "Priority": 500024, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://api.ukuapi88.com/api.php/provide/vod/?ac=list" },

  { "id": "src-非凡资源", "name": "非凡资源", "Top": true, "Search": true, "Priority": 500025, "note": "use_proxy=true enabled=true is_custom=true", "api": "http://ffzy5.tv/api.php/provide/vod" },
  { "id": "src-卧龙资源", "name": "卧龙资源", "Top": true, "Search": true, "Priority": 500026, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://wolongzyw.com/api.php/provide/vod" },
  { "id": "src-最大资源", "name": "最大资源", "Top": true, "Search": true, "Priority": 500027, "note": "use_proxy=true enabled=true is_custom=true", "api": "https://api.zuidapi.com/api.php/provide/vod" },

  { "id": "src-155", "name": "155", "Top": false, "Search": true, "Priority": 510038, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://155api.com/api.php/provide/vod" },
  { "id": "src-CK", "name": "CK", "Top": false, "Search": true, "Priority": 510036, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://www.ckzy1.com/api.php/provide/vod" },
  { "id": "src-jkun", "name": "jkun", "Top": false, "Search": true, "Priority": 510037, "note": "use_proxy=false enabled=true is_custom=true", "api": "https://jkunzyapi.com/api.php/provide/vod" }
